Feature/core 541 permissions ui
evannetwork/ui-vue pull request #16
Opened 2019-10-10 15:52 UTC by karladler

do not merge yet, a few stylings for permission-editor are still missing. Logic can be already be tested and reviewed.

2019-10-14 06:24 UTC, wulfraem requested changes
^^

2019-10-14 06:24 UTC, wulfraem commented on dapps/evancore.vue.libs/src/i18n/de.ts
> +      "noContacts": "Sie haben keine Kontakte in ihrem Adressbuch, bitte fügen Sie zuerst einen Kontakt hinzu."
```suggestion
      "noContacts": "Sie haben keine Kontakte in Ihrem Adressbuch, bitte fügen Sie zuerst einen Kontakt hinzu."
```

2019-10-14 10:14 UTC, DanielMaass commented on dapps/evancore.vue.libs/src/components/permissions-editor/permissions-editor.ts
> +interface PermissionsInterface {
interface should define in one place. Maybe in permissions.ts

2019-10-14 10:14 UTC, DanielMaass commented on dapps/evancore.vue.libs/src/components/permissions-editor/permissions-editor.vue
> +    </p>
we should support localization

2019-10-14 10:14 UTC, DanielMaass commented on dapps/evancore.vue.libs/src/components/permissions/permissions.ts
> +    fields: string[]
maybe define as optional "fields?: string[]"

2019-10-14 10:14 UTC, DanielMaass commented on dapps/evancore.vue.libs/src/components/permissions/permissions.ts
> +    default: ''
set as required as well

2019-10-14 10:14 UTC, DanielMaass commented on dapps/evancore.vue.libs/src/components/permissions/permissions.vue
> +      <p class="p-6 text-error">No permisisons available to edit.</p>
support localization

2019-10-15 11:38 UTC, DanielMaass approved these changes

2019-10-15 11:39 UTC, merged