Feature/core 702 onboarding feedback
evannetwork/ui-vue pull request #50
Opened 2019-11-20 15:24 UTC by Tschuck

2019-11-21 14:20 UTC, datrinh requested changes

2019-11-21 14:20 UTC, datrinh commented on dapps/evancore.vue.libs/src/components/forms/form/form.ts
> +          (control.uiSpecs.attr && control.uiSpecs.attr.hasOwnProperty(type)))
I would consider refactoring into a small check function when you need 3 lines in the if-bracket

2019-11-21 14:20 UTC, datrinh commented on dapps/evancore.vue.libs/src/i18n/de.json
> +    "password-placeholder": "Passwort der Profilerstellung",
Warum nicht einfach Passwort? Ist der Rest nicht redundant?

2019-11-21 14:20 UTC, datrinh commented on dapps/evancore.vue.libs/src/i18n/en.json
> +    "password-placeholder": "Password from sign up",
Same here

2019-11-21 14:20 UTC, datrinh commented on dapps/evancore.vue.libs/src/components/profile/profile-preview/profile-preview.ts
> +  setOriginalUserInfo() {
I'd rename this. Functions starting with "set" will be expected to be setters. This is more of a "resetter" or "restorer".

2019-11-21 16:23 UTC, datrinh requested changes

2019-11-21 16:23 UTC, datrinh commented on dapps/evancore.vue.libs/src/components/forms/form/form.ts
> +   * Overwrites a control a specific attribute.
This comment wording seems confusing? :)

2019-11-22 07:09 UTC, Tschuck commented on dapps/evancore.vue.libs/src/components/forms/form/form.ts
> +   * Overwrites a control a specific attribute.
Looks like i fall asleep while writing this :D

2019-11-22 07:13 UTC, merged